Remove hashes from pip files
Albeit it's best practice to keep and verify package hashes, the way
it's done in Python/pip is too unwieldy to use. There are so many hashes
for a single package, often OS dependent, there's no good tooling to
keep them up to date, or even gather all of the hashes for the different
OS and Python variants, they're cluttering the requirements files, since
pip doesn't maintain the hashes in some separate lock file ...

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -23,7 +23,7 @@ docs: .require-mkdocs cli
 .PHONY: .require-mkdocs
 .require-mkdocs:
 	@which mkdocs >/dev/null 2>/dev/null || { \
-	  echo 'mkdocs required, use pip install --disable-pip-version-check --require-hashes -r $(CURDIR)/requirements.txt' >&2; \
+	  echo 'mkdocs required, use pip install --disable-pip-version-check -r $(CURDIR)/requirements.txt' >&2; \
 	  exit 1; \
 	}
 
