Revise local docs testing setup
Integrate the dockerized docs testing setup into the main Makefile.
Don't require docker-compose to run it and allow an easy override of the
local HTTP port.

* Add Makefile.variables to capture the following:
  * Python version
  * k0s releases GitHub API URL
* Make the mkdocs check dependent on the docs goal
  So that other targets in the Makefile may be used without mkdocs
* Fix the handling of TARGET_VERSION
  The latest release and specific releases require different URLs.
* Add support to build the docs using the local k0s binary
  Use TARGET_VERSION=local for this
* Add caching support for downloaded k0s binaries
  This is done via curl's ETag HTTP header support.
* Remove superfluous Node.js steps from docs actions.
* Add basic support for building docs on Windows

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -1,7 +1,4 @@
-mkdocs := $(shell which mkdocs)
-ifeq ($(mkdocs),)
-@echo "mkdocs required, use pip install mkdocs"
-endif
+include Makefile.variables
 
 ifeq ($(OS),Windows_NT)
 detected_OS := windows
@@ -19,28 +16,78 @@ TARGET_VERSION ?= latest
 # mkdocs.yml refuses to live in the docs-directory, this is why "cd .." is needed
 # gives: "Error: The 'docs_dir' should not be the parent directory of the config file."
 # even if docs_dir is "."
-docs: cli
+docs: .require-mkdocs cli
 	cd .. && mkdocs build --strict
 
-LATEST_RELEASE_META_URL=https://api.github.com/repos/k0sproject/k0s/releases/$(TARGET_VERSION)
-JQ_COMMAND=jq -r '.assets[]|select(.browser_download_url|contains("amd64"))|select(.browser_download_url|contains(".exe")|not)|select(.browser_download_url|contains("bundle")|not).browser_download_url'
+.PHONY: .require-mkdocs
+.require-mkdocs:
+	@which mkdocs >/dev/null 2>/dev/null || { \
+	  echo 'mkdocs required, use pip install mkdocs' >&2; \
+	  exit 1; \
+	}
 
-.PHONY: k0s_release_binary
-k0s_release_binary:
-	curl -L -o ./k0s `curl $(LATEST_RELEASE_META_URL) | $(JQ_COMMAND)`
-	chmod +x ./k0s
+.PHONY: .k0s-download-url .k0s.exe-download-url
+ifeq ($(TARGET_VERSION),latest)
+.k0s-download-url .k0s.exe-download-url: release_metadata_url = $(k0s_releases_url)/latest
+else
+.k0s-download-url .k0s.exe-download-url: release_metadata_url = $(k0s_releases_url)/tags/$(TARGET_VERSION)
+endif
+.k0s-download-url .k0s.exe-download-url:
+	$(eval binary_suffix = $(patsubst .k0s%,%,$(@:-download-url=)))
+	curl -sS -- '$(release_metadata_url)' \
+	  | jq -r '. as {name: $$ver, assets: $$a} | $$a[] | select(.name == "k0s-"+$$ver+"-amd64$(binary_suffix)") | .browser_download_url'
+
+.PHONY: k0s k0s.exe
+ifeq ($(TARGET_VERSION),local)
+cli: k0s_binary_path := $(abspath ..)
+else
+cli: k0s_binary_path := $(abspath .)
+k0s k0s.exe::
+	[ ! -f '$@.etag' ] || { if [ ! -f '$@' ] || [ '$@.etag' -ot '$@' ]; then rm -- '$@.etag'; fi }
+	touch -- '$@.etag'
+	@downloadUrl="$$($(MAKE) --no-print-directory -s '.$@-download-url')" \
+	  && echo "Download URL for $@ $(TARGET_VERSION): $$downloadUrl" \
+	  && curl -Lo '$@.tmp' --etag-compare '$@.etag' --etag-save '$@.etag.tmp' -- "$$downloadUrl"
+	if [ -f '$@.tmp' ]; then \
+	  mv -- '$@.tmp' '$@' && touch -r '$@' -- '$@.etag.tmp'; \
+	fi
+	mv -- '$@.etag.tmp' '$@.etag'
+
+k0s::
+	chmod +x -- '$@'
+endif
 
 .PHONY: cli
-cli: k0s_release_binary
+ifeq ($(detected_OS),windows)
+cli: k0s.exe
+cli: k0s_binary = k0s.exe
+else
+cli: k0s
+cli: k0s_binary = k0s
+endif
+cli:
 	rm -rf cli
 	mkdir cli
-	cd .. && ./docs/k0s docs markdown
-	rm ./k0s
+	cd .. && '$(k0s_binary_path)/$(k0s_binary)' docs markdown
 	rm cli/k0s_kubectl_*
 	sed $(sedopt) '/\[k0s kubectl /d' cli/k0s_kubectl.md
 	ln -s k0s.md cli/README.md
 
+.docker-image.serve-dev.stamp: Dockerfile.serve-dev requirements.txt
+	docker build \
+	  --build-arg PYTHON_IMAGE_VERSION=$(python_version)-alpine3.15 \
+	  -t 'k0sdocs$(basename $@)' -f '$<' .
+	touch -- '$@'
+
+clean-k0s:
+	rm -f k0s k0s.exe k0s.etag k0s.exe.etag
+
 .PHONY: clean
-clean:
+clean: clean-k0s
 	rm -rf cli
 	rm -rf ../site
+	for i in .docker-image.*.stamp; do \
+	  if [ -f "$$i" ]; then \
+	    docker rmi -f "k0sdocs$$(basename "$$i" .stamp)" && rm -- "$$i";\
+	  fi; \
+	done
