Add basic Windows smoketest
The tests setups a WSL Linux on Windows runner which allow us to run the CP (with worker enabled) on the Linux node.
The Windows host is used as a worker node.

There's bunch of preliminary steps in order to configure networking, WSL and other stuff so that the test would be as stable as possible.
The current challenge is that when Calico boots up on the Windows side, it'll create the overlay network which in turn creates bit of a flip on the general networking.

Signed-off-by: Jussi Nummelin <jnummelin@mirantis.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -235,235 +235,246 @@ jobs:
             echo Trimming Go cache
             find build/cache/go/build -type f \( -name '*-a' -o -name '*-d' \) -not -newer build/cache/_cache_sentinel -delete
           fi
+  # FIXME: Temporarily disabling smoketest jobs to reduce load on GH runners while iterating on windows tests
+  # smoketests:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       smoke-suite: ${{ fromJson(needs.prepare.outputs.smoketest-matrix) }}
 
-  smoketests:
-    strategy:
-      fail-fast: false
-      matrix:
-        smoke-suite: ${{ fromJson(needs.prepare.outputs.smoketest-matrix) }}
+  #   name: "check-${{ matrix.smoke-suite }} :: amd64"
+  #   needs:
+  #     - prepare
+  #     - build-k0s
+  #     - build-airgap-image-bundle
+  #     - build-ipv6-test-image-bundle
 
-    name: "check-${{ matrix.smoke-suite }} :: amd64"
-    needs:
-      - prepare
-      - build-k0s
-      - build-airgap-image-bundle
-      - build-ipv6-test-image-bundle
+  #   uses: ./.github/workflows/smoketest.yaml
+  #   with:
+  #     arch: amd64
+  #     name: ${{ matrix.smoke-suite }}
 
-    uses: ./.github/workflows/smoketest.yaml
-    with:
-      arch: amd64
-      name: ${{ matrix.smoke-suite }}
+  # smoketests-linux-arm64:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       smoke-suite:
+  #         - airgap
+  #         - basic
+  #         - network-conformance-calico
+  #         - network-conformance-kuberouter
 
-  smoketests-linux-arm64:
-    strategy:
-      fail-fast: false
-      matrix:
-        smoke-suite:
-          - airgap
-          - basic
-          - network-conformance-calico
-          - network-conformance-kuberouter
+  #   name: "check-${{ matrix.smoke-suite }} :: arm64"
+  #   needs: [build-k0s, build-airgap-image-bundle]
 
-    name: "check-${{ matrix.smoke-suite }} :: arm64"
-    needs: [build-k0s, build-airgap-image-bundle]
+  #   uses: ./.github/workflows/smoketest.yaml
+  #   with:
+  #     arch: arm64
+  #     name: ${{ matrix.smoke-suite }}
 
-    uses: ./.github/workflows/smoketest.yaml
-    with:
-      arch: arm64
-      name: ${{ matrix.smoke-suite }}
+  # autopilot-tests:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       version: ${{fromJson(needs.prepare.outputs.autopilot-matrix)}}
+  #       smoke-suite:
+  #         - controllerworker
+  #         - ha3x3
 
-  autopilot-tests:
-    strategy:
-      fail-fast: false
-      matrix:
-        version: ${{fromJson(needs.prepare.outputs.autopilot-matrix)}}
-        smoke-suite:
-          - controllerworker
-          - ha3x3
+  #   name: "check-ap-${{ matrix.smoke-suite }} :: ${{ matrix.version }}"
+  #   needs: [prepare, build-k0s]
 
-    name: "check-ap-${{ matrix.smoke-suite }} :: ${{ matrix.version }}"
-    needs: [prepare, build-k0s]
+  #   uses: ./.github/workflows/smoketest.yaml
+  #   with:
+  #     arch: amd64
+  #     name: ap-${{ matrix.smoke-suite }}
+  #     k0s-reference-version: ${{ matrix.version }}
 
-    uses: ./.github/workflows/smoketest.yaml
-    with:
-      arch: amd64
-      name: ap-${{ matrix.smoke-suite }}
-      k0s-reference-version: ${{ matrix.version }}
+  # build-arm:
+  #   name: "Build :: k0s :: arm"
+  #   if: github.repository == 'k0sproject/k0s'
+  #   runs-on:
+  #     - self-hosted
+  #     - linux
+  #     - arm
+  #   steps:
+  #     # https://github.com/actions/checkout/issues/273#issuecomment-642908752 (see below)
+  #     - name: "Pre: Fixup directories"
+  #       run: find . -type d -not -perm /u+w -exec chmod u+w '{}' \;
 
-  build-arm:
-    name: "Build :: k0s :: arm"
-    if: github.repository == 'k0sproject/k0s'
-    runs-on:
-      - self-hosted
-      - linux
-      - arm
-    steps:
-      # https://github.com/actions/checkout/issues/273#issuecomment-642908752 (see below)
-      - name: "Pre: Fixup directories"
-        run: find . -type d -not -perm /u+w -exec chmod u+w '{}' \;
+  #     - name: Check out code into the Go module directory
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # for `git describe`
+  #         persist-credentials: false
 
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # for `git describe`
-          persist-credentials: false
+  #     - name: Prepare build environment
+  #       run: .github/workflows/prepare-build-env.sh
 
-      - name: Prepare build environment
-        run: .github/workflows/prepare-build-env.sh
+  #     - name: Set up Go
+  #       uses: actions/setup-go@v3
+  #       with:
+  #         go-version: ${{ env.GO_VERSION }}
 
-      - name: Set up Go
-        # https://github.com/actions/setup-go/pull/666
-        uses: actions/setup-go@b551c4cd70271da7ce09faf55f722b5e270c54d1
-        with:
-          go-version: ${{ env.GO_VERSION }}
-          cache: false
+  #    - name: Set up Go
+  #      # https://github.com/actions/setup-go/pull/666
+  #      uses: actions/setup-go@b551c4cd70271da7ce09faf55f722b5e270c54d1
+  #      with:
+  #        go-version: ${{ env.GO_VERSION }}
+  #        cache: false
+  #     - name: Cache embedded binaries
+  #       id: cache-embedded-bins
+  #       uses: actions/cache@v4
+  #       with:
+  #         key: "build-k0s-linux-arm-embedded-bins-${{ hashFiles('embedded-bins/**/*') }}"
+  #         path: embedded-bins/staging/linux/bin/
 
-      - name: Cache embedded binaries
-        id: cache-embedded-bins
-        uses: actions/cache@v4
-        with:
-          key: "build-k0s-linux-arm-embedded-bins-${{ hashFiles('embedded-bins/**/*') }}"
-          path: embedded-bins/staging/linux/bin/
+  #     - name: Cache Go cache
+  #       id: cache-gocache
+  #       uses: actions/cache@v4
+  #       with:
+  #         key: "build-k0s-linux-arm-gocache-go${{ env.GO_VERSION }}-${{ github.sha }}"
+  #         restore-keys: "build-k0s-linux-arm-gocache-go${{ env.GO_VERSION }}-"
+  #         path: build/cache/go/build
 
-      - name: Cache Go cache
-        id: cache-gocache
-        uses: actions/cache@v4
-        with:
-          key: "build-k0s-linux-arm-gocache-go${{ env.GO_VERSION }}-${{ github.sha }}"
-          restore-keys: "build-k0s-linux-arm-gocache-go${{ env.GO_VERSION }}-"
-          path: build/cache/go/build
+  #     - name: Prepare Go cache
+  #       if: steps.cache-gocache.outputs.cache-hit
+  #       run: |
+  #         touch -t "$(TZ=UTC+24 date +%Y%m%d%H%M.%S)" build/cache/_cache_sentinel
+  #         find build/cache/go/build -type f \( -name '*-a' -o -name '*-d' \) -exec touch -r build/cache/_cache_sentinel {} +
 
-      - name: Prepare Go cache
-        if: steps.cache-gocache.outputs.cache-hit
-        run: |
-          touch -t "$(TZ=UTC+24 date +%Y%m%d%H%M.%S)" build/cache/_cache_sentinel
-          find build/cache/go/build -type f \( -name '*-a' -o -name '*-d' \) -exec touch -r build/cache/_cache_sentinel {} +
+  #     - name: Build
+  #       env:
+  #         EMBEDDED_BINS_CACHED: "${{ steps.cache-embedded-bins.outputs.cache-hit }}"
+  #       run: |
+  #         gh --version || echo No gh installed
+  #         make .k0sbuild.docker-image.k0s
+  #         touch go.sum
+  #         if [ "$EMBEDDED_BINS_CACHED" == true ]; then
+  #           make --touch .bins.linux.stamp
+  #         fi
+  #         make bindata
+  #         make --touch codegen
+  #         make build
+  #         echo "k0s binary size: **$(du -sh k0s | cut -f1)**" >>$GITHUB_STEP_SUMMARY
 
-      - name: Build
-        env:
-          EMBEDDED_BINS_CACHED: "${{ steps.cache-embedded-bins.outputs.cache-hit }}"
-        run: |
-          gh --version || echo No gh installed
-          make .k0sbuild.docker-image.k0s
-          touch go.sum
-          if [ "$EMBEDDED_BINS_CACHED" == true ]; then
-            make --touch .bins.linux.stamp
-          fi
-          make bindata
-          make --touch codegen
-          make build
-          echo "k0s binary size: **$(du -sh k0s | cut -f1)**" >>$GITHUB_STEP_SUMMARY
+  #     - name: Upload compiled executable
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: k0s-arm
+  #         path: k0s
 
-      - name: Upload compiled executable
-        uses: actions/upload-artifact@v4
-        with:
-          name: k0s-arm
-          path: k0s
+  #     - name: Unit tests
+  #       run: make check-unit
 
-      - name: Unit tests
-        run: make check-unit
+  #     - name: Create airgap image list
+  #       run: make airgap-images.txt
 
-      - name: Create airgap image list
-        run: make airgap-images.txt
+  #     - name: Cache airgap image bundle
+  #       id: cache-airgap-image-bundle
+  #       uses: actions/cache@v4
+  #       with:
+  #         key: airgap-image-bundle-linux-arm-${{ hashFiles('Makefile', 'airgap-images.txt', 'cmd/airgap/*', 'pkg/airgap/*') }}
+  #         path: |
+  #           airgap-images.txt
+  #           airgap-image-bundle-linux-arm.tar
 
-      - name: Cache airgap image bundle
-        id: cache-airgap-image-bundle
-        uses: actions/cache@v4
-        with:
-          key: airgap-image-bundle-linux-arm-${{ hashFiles('Makefile', 'airgap-images.txt', 'cmd/airgap/*', 'pkg/airgap/*') }}
-          path: |
-            airgap-images.txt
-            airgap-image-bundle-linux-arm.tar
+  #     - name: Create airgap image bundle if not cached
+  #       if: steps.cache-airgap-image-bundle.outputs.cache-hit != 'true'
+  #       run: make airgap-image-bundle-linux-arm.tar
 
-      - name: Create airgap image bundle if not cached
-        if: steps.cache-airgap-image-bundle.outputs.cache-hit != 'true'
-        run: make airgap-image-bundle-linux-arm.tar
+  #     - name: Upload airgap bundle
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: airgap-image-bundle-linux-arm.tar
+  #         path: airgap-image-bundle-linux-arm.tar
 
-      - name: Upload airgap bundle
-        uses: actions/upload-artifact@v4
-        with:
-          name: airgap-image-bundle-linux-arm.tar
-          path: airgap-image-bundle-linux-arm.tar
+  #     - name: Trim Go cache
+  #       if: steps.cache-gocache.outputs.cache-hit
+  #       run: |
+  #         find build/cache/go/build -type f \( -name '*-a' -o -name '*-d' \) -not -newer build/cache/_cache_sentinel -delete
 
-      - name: Trim Go cache
-        if: steps.cache-gocache.outputs.cache-hit
-        run: |
-          find build/cache/go/build -type f \( -name '*-a' -o -name '*-d' \) -not -newer build/cache/_cache_sentinel -delete
+  # # TODO We probably want to separate the smoketest into a separate callable workflow which we can call from the build step
+  # # This way we could actually fully parallelize the build and smoketest steps. Currently we are limited by the fact that
+  # # smoke-test step only start after both arm and armv7 builds have finished.
+  # smoketest-arm:
+  #   name: "${{ matrix.test }} :: arm"
+  #   if: github.repository == 'k0sproject/k0s'
+  #   needs: [build-arm]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       test:
+  #         - check-basic
+  #         - check-calico
+  #         - check-airgap
+  #   runs-on:
+  #     - self-hosted
+  #     - linux
+  #     - arm
 
-  # TODO We probably want to separate the smoketest into a separate callable workflow which we can call from the build step
-  # This way we could actually fully parallelize the build and smoketest steps. Currently we are limited by the fact that
-  # smoke-test step only start after both arm and armv7 builds have finished.
-  smoketest-arm:
-    name: "${{ matrix.test }} :: arm"
-    if: github.repository == 'k0sproject/k0s'
-    needs: [build-arm]
-    strategy:
-      fail-fast: false
-      matrix:
-        test:
-          - check-basic
-          - check-calico
-          - check-airgap
-    runs-on:
-      - self-hosted
-      - linux
-      - arm
+  #   steps:
+  #     - name: Check out code into the Go module directory
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # for `git describe`
+  #         persist-credentials: false
 
-    steps:
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # for `git describe`
-          persist-credentials: false
+  #     - name: Prepare build environment
+  #       run: .github/workflows/prepare-build-env.sh
 
-      - name: Prepare build environment
-        run: .github/workflows/prepare-build-env.sh
+  #     - name: Set up Go
+  #       uses: actions/setup-go@v3
+  #       with:
+  #         go-version: ${{ env.GO_VERSION }}
 
+<<<<<<< HEAD
       - name: Set up Go
         uses: actions/setup-go@v6
         with:
           go-version: ${{ env.GO_VERSION }}
           cache: false
+=======
+  #     - name: Download compiled binary
+  #       uses: actions/download-artifact@v5
+  #       with:
+  #         name: k0s-arm
+>>>>>>> a778557f1 (Add basic Windows smoketest)
 
-      - name: Download compiled binary
-        uses: actions/download-artifact@v5
-        with:
-          name: k0s-arm
+  #     - name: k0s sysinfo
+  #       run: |
+  #         chmod +x k0s
+  #         ./k0s sysinfo
 
-      - name: k0s sysinfo
-        run: |
-          chmod +x k0s
-          ./k0s sysinfo
+  #     - name: Download airgap bundle
+  #       if: contains(matrix.test, 'airgap')
+  #       uses: actions/download-artifact@v5
+  #       with:
+  #         name: airgap-image-bundle-linux-arm.tar
 
-      - name: Download airgap bundle
-        if: contains(matrix.test, 'airgap')
-        uses: actions/download-artifact@v5
-        with:
-          name: airgap-image-bundle-linux-arm.tar
+  #     - name: Run smoketest
+  #       run: make -C inttest ${{ matrix.test }}
 
-      - name: Run smoketest
-        run: make -C inttest ${{ matrix.test }}
+  #     - name: Collect k0s logs and support bundle
+  #       if: failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: smoketest-arm-check-basic-files
+  #         path: |
+  #           /tmp/*.log
+  #           /tmp/support-bundle.tar.gz
 
-      - name: Collect k0s logs and support bundle
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: smoketest-arm-check-basic-files
-          path: |
-            /tmp/*.log
-            /tmp/support-bundle.tar.gz
+  #     # https://github.com/actions/checkout/issues/273#issuecomment-642908752
+  #     # Golang mod cache tends to set directories to read-only, which breaks any
+  #     # attempts to simply remove those directories. The `make clean-gocache`
+  #     # target takes care of this, but the mod cache can't be deleted here,
+  #     # since it shall be cached across builds, and caching takes place as a
+  #     # post build action. So, as a workaround, ensure that all subdirectories
+  #     # are writable.
+  #     - name: "Post: Fixup directories"
+  #       if: always()
+  #       run: find . -type d -not -perm /u+w -exec chmod u+w '{}' \;
 
-      # https://github.com/actions/checkout/issues/273#issuecomment-642908752
-      # Golang mod cache tends to set directories to read-only, which breaks any
-      # attempts to simply remove those directories. The `make clean-gocache`
-      # target takes care of this, but the mod cache can't be deleted here,
-      # since it shall be cached across builds, and caching takes place as a
-      # post build action. So, as a workaround, ensure that all subdirectories
-      # are writable.
-      - name: "Post: Fixup directories"
-        if: always()
-        run: find . -type d -not -perm /u+w -exec chmod u+w '{}' \;
-
-      - name: "Docker prune"
-        if: always()
-        run: docker system prune --force --filter "until=$((24*7))h"
+  #     - name: "Docker prune"
+  #       if: always()
+  #       run: docker system prune --force --filter "until=$((24*7))h"
